#-----------------------------------------------------------------------------------------------#
#       .NET Core .csproj files patching (see doc of AppVeyor)     #
#-----------------------------------------------------------------------------------------------#

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'


#---------------------------------#
#  Build Script                   #
#---------------------------------#

build_script:
  - ps: .\build.ps1 --bootstrap
  # - ps: .\build.ps1 -Target AppVeyor
  
#-----------------------------------------------------------------------------------------------#
#        Branches to build (e.g.  master, develop, release, hotfix) hier only master branch     #
#-----------------------------------------------------------------------------------------------#

branches:
  only:
    - master
    
#---------------------------------#
#  Build Cache                    #
#---------------------------------#

cache:
- src\packages -> src\**\packages.config
