name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build ON release
        run: dotnet build -c Release --no-restore
      - name: Test ON Debug
        run: dotnet test -c Debug --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      - name: Test ON Release
        run: dotnet test -c Release --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
